/* 1. Marks */
// var eng = Number(prompt('enter your marks in english'))

// var maths = Number(prompt('enter your marks in maths'))

// var sci = Number(prompt('enter your marks in sci'))

// var hindi = Number(prompt('enter your marks in hindi'))

// var marathi = Number(prompt('enter your marks in marathi'))

// var total = (eng + maths + sci + hindi + marathi)

// document.write(total, 'total marks','<br>')

// var percentage = (total / 500) * 100

// document.write(percentage, 'your percentage % <br>')

// if (percentage >= 85 && percentage <= 100) {
//     document.write('A grade')
// }

// else if (percentage >= 70 && percentage < 85) {
//     document.write('B grade')
// }

// else if (percentage >= 60 && percentage < 70) {
//     document.write('C grade')
// }

// else if (percentage >= 45 && percentage < 70) {
//     document.write('D grade')
// }

// else if (percentage >= 35 && percentage < 45) {
//     document.write('E grade')
// }

// else if (percentage < 35 && percentage >= 0) {
//     print('Fail')
// }

// else {
//     document.write('enter valid marks')
// }


/* 13 Assignment */

/* 1. JavaScript Program to Calculate the Area of a Triangle. */

var baseValue = prompt('Enter the base of a triangle: ');
var heightValue = prompt('Enter the height of a triangle: ');

// calculate the area
var areaValue = (baseValue * heightValue) / 2;

document.write(
  `The area of the triangle is ${areaValue}`
);


/* 2. Javascript Program to Check if a number is Positive, Negative, or Zero. */

// program that checks if the number is positive, negative or zero
// input from the user
const number = parseInt(prompt("Enter a number: "));

// check if number is greater than 0
if (number > 0) {
    document.write("The number is positive");
}

// check if number is 0
else if (number == 0) {
    document.write("The number is zero");
}

// if number is less than 0
else {
    document.write("The number is negative");
}


/* 3. JavaScript Program to Guess a Random Number */

// program where the user has to guess a number generated by a program
function guessNumber() {

    // generating a random integer from 1 to 10
    const random = Math.floor(Math.random() * 10) + 1;

    // take input from the user
    let number = parseInt(prompt('Guess a number from 1 to 10: '));

    // take the input until the guess is correct
    while (number !== random) {
        number = parseInt(prompt('Guess a number from 1 to 10: '));
    }

    // check if the guess is correct
    if (number == random) {
        document.write('You guessed the correct number.');
    }

}

// call the function
guessNumber();